version: '3'

services:
  traefik-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"
      - "8090:8080" # The Web UI (enabled by --api)
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - $HOME/workspace/traefik/traefik.toml:/traefik.toml
      - $HOME/workspace/traefik/acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.valdepeace.com
      - traefik.port=8080
      - treafik.backend=traefik-monitor


networks:
  traefik-net:
    external:
      name: traefik-proxy
