version: "3"

services:
  node-red:
    image: nodered/node-red-docker
    container_name: node-red
    ports:
      - "1880:1880"
    labels:
      - traefik.backend=node-red
      - traefik.enable=true
      - traefik.frontend.rule=Host:test01.valdepeace.com
      - traefik.port=1880
    networks:
      - traefik-net

networks:
  traefik-net:
    external:
      name: traefik-proxy