version: "3"

services:
  node-red:
    image: nodered/node-red-docker
    container_name: node-red
    ports:
      - "1880:1880"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.backend=node-red"
      - "traefik.backend.stickness=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.port=1880"
      - "traefik.frontend.rule=Host:test02.valdepeace.com"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net
    volumes:
      - flows:/data

networks:
  traefik-net:
    external: true
volumes:
  flows: